apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nirmata-hostpath-provisioner
  name: nirmata-hostpath-provisioner
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: nirmata-hostpath-provisioner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: nirmata-hostpath-provisioner
    spec:
      containers:
      - env:
        - name: LEADER_ELECTION
          value: flase
        - name: ZK_PV_DIR
          value: /mnt/nirmata/zk
        - name: MONGODB_PV_DIR
          value: /mnt/nirmata/mongodb
        - name: KAFKA_PV_DIR
          value: /mnt/nirmata/kafka
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: ghcr.io/nirmata/hostpath-provisioner:pe-2.11.8
        imagePullPolicy: IfNotPresent
        name: nirmata-hostpath-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/hostpath-provisioner
          name: pv-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nirmata-hostpath-provisioner
      serviceAccountName: nirmata-hostpath-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /tmp/hostpath-provisioner
          type: ""
        name: pv-volume
