apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: nirmata-hostpath-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nirmata-hostpath-provisioner
subjects:
- kind: ServiceAccount
  name: nirmata-hostpath-provisioner
  namespace: kube-system
