apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
  name: leader-locking-hostpath-provisioner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-locking-hostpath-provisioner
subjects:
- kind: ServiceAccount
  name: nirmata-hostpath-provisioner
  namespace: kube-system
